/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import org.web3j.protocol.core.methods.response.Transaction;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.IOException;
import java.util.ArrayList;
import java.util.concurrent.ExecutionException;

/**
 *
 * @author Youssef Ziad
 */
public class AdvancedScreen extends JFrame {

    public JFrame parentFrame;

    /**
     * Creates new form MainScreen
     */
    public AdvancedScreen() {

        initComponents();
    }

    public AdvancedScreen(String key, JFrame m) throws ExecutionException, InterruptedException, IOException {
        initComponents();
        parentFrame = m;
        QueryResult.setText("Query Results: ("+key+")");
        ArrayList<ArrayList<Object>> everything = EthereumExplorer.parse(key);
        //DefaultTableModel tm = new DefaultTableModel(everything.size(),everything.get(0).size()+1);
        ArrayList<Object> attNames = everything.remove(0);
        Object[][] outer = new Object[everything.size()][everything.get(0).size()+1];
        for(int i = 0; i < everything.size(); i++){
            outer[i][0] = i+1;
            for(int j = 0; j< everything.get(i).size(); j++){
                outer[i][j+1] = everything.get(i).get(j);
            }
        }
        Object[] attNames2 = new Object[attNames.size()+1];
        attNames2[0] = "Number";
        for(int i = 0; i < attNames.size(); i++){
            attNames2[i+1] = attNames.get(i);
        }
        DefaultTableModel tm = new DefaultTableModel(outer,attNames2);
        jTable1.setModel(tm);

        /*for(int i = 0; i < everything.size(); i++){
            jTable1.getModel().setValueAt(i+1,i,0);
            for(int j = 0; j< everything.get(i).size(); j++){
                jTable1.getModel().setValueAt(everything.get(i).get(j),i,j+1);
            }
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        SkyScraper = new JLabel();
        QueryResult = new JLabel();
        BackButton = new JButton();
        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();
        Background = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        SkyScraper.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        SkyScraper.setForeground(new java.awt.Color(255, 255, 255));
        SkyScraper.setText("SkyScraper");
        jPanel1.add(SkyScraper);
        SkyScraper.setBounds(30, 20, 190, 42);

        QueryResult.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QueryResult.setForeground(new java.awt.Color(255, 255, 255));
        QueryResult.setText("Query Result:");
        jPanel1.add(QueryResult);
        QueryResult.setBounds(30, 90, 500, 17);

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(1280, 730, 73, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 130, 452, 170);

        Background.setIcon(new ImageIcon(getClass().getResource("/etherbkg.png"))); // NOI18N
        Background.setLabelFor(jPanel1);
        jPanel1.add(Background);
        Background.setBounds(0, 0, 1366, 768);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        parentFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton BackButton;
    private JLabel Background;
    private JLabel QueryResult;
    private JLabel SkyScraper;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    private JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
