/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import org.web3j.protocol.core.methods.response.EthBlock;
import org.web3j.protocol.core.methods.response.Transaction;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.ExecutionException;

/**
 *
 * @author Youssef Ziad
 */
public class BlockScreen extends JFrame {

    public JFrame parentFrame;

    /**
     * Creates new form MainScreen
     */
    public BlockScreen() {

        initComponents();
    }

    public BlockScreen(String key, JFrame m) throws ExecutionException, InterruptedException, IOException {
        initComponents();
        parentFrame = m;
        Hash.setText(key);
        EthBlock.Block b = EthereumExplorer.getBlockbyHash(key);
        Block.setText(b.getNumber()+"");
        Difficulty.setText(b.getDifficulty()+"");
        PHash.setText(b.getParentHash());
        NoTrans.setText(b.getTransactions().size()+"");
        Miner.setText(b.getMiner());
        GasLimit.setText(b.getGasLimit()+"");
        GasUsed.setText(b.getGasUsed()+"");
        Background.setLayout(null);
        List<EthBlock.TransactionResult> x = b.getTransactions();
        for(int i = 0; i < x.size(); i++){
            Transaction t = (Transaction) x.get(i).get();
            TButton tbu = new TButton(t,this);
            Background.add(tbu);
            tbu.setBounds(60,300+30*i,400,30);
        }
        revalidate();
        repaint();
    }

    public BlockScreen(int num, JFrame m) throws ExecutionException, InterruptedException, IOException {
        initComponents();
        parentFrame = m;
        Block.setText(num+"");
        EthBlock.Block b = EthereumExplorer.getBlockbyNumber(num);
        Hash.setText(b.getHash());
        Difficulty.setText(b.getDifficulty()+"");
        PHash.setText(b.getParentHash());
        NoTrans.setText(b.getTransactions().size()+"");
        Miner.setText(b.getMiner());
        GasLimit.setText(b.getGasLimit()+"");
        GasUsed.setText(b.getGasUsed()+"");
        Background.setLayout(null);
        List<EthBlock.TransactionResult> x = b.getTransactions();
        for(int i = 0; i < x.size(); i++){
            Transaction t = (Transaction) x.get(i).get();
            TButton tbu = new TButton(t,this);
            Background.add(tbu);
            tbu.setBounds(60,300+30*i,400,30);
        }
        revalidate();
        repaint();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        SkyScraper = new JLabel();
        NoTrans = new JLabel();
        Hash = new JLabel();
        BlockDetails = new JLabel();
        Hash1 = new JLabel();
        NoTrans1 = new JLabel();
        Block1 = new JLabel();
        Block = new JLabel();
        Miner1 = new JLabel();
        Miner = new JLabel();
        Difficulty1 = new JLabel();
        Difficulty = new JLabel();
        GasUsed1 = new JLabel();
        GasUsed = new JLabel();
        GasLimit1 = new JLabel();
        GasLimit = new JLabel();
        BackButton = new JButton();
        PHash1 = new JLabel();
        PHash = new JLabel();
        Transactions = new JLabel();
        Background = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        SkyScraper.setFont(new Font("Trebuchet MS", 1, 36)); // NOI18N
        SkyScraper.setForeground(new Color(255, 255, 255));
        SkyScraper.setText("SkyScraper");
        jPanel1.add(SkyScraper);
        SkyScraper.setBounds(30, 20, 190, 42);

        NoTrans.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        NoTrans.setForeground(new Color(255, 255, 255));
        NoTrans.setText("[TCount]");
        jPanel1.add(NoTrans);
        NoTrans.setBounds(180, 180, 130, 15);

        Hash.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        Hash.setForeground(new Color(255, 255, 255));
        Hash.setText("[Hash]");
        jPanel1.add(Hash);
        Hash.setBounds(180, 120, 130, 15);

        BlockDetails.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        BlockDetails.setForeground(new Color(255, 255, 255));
        BlockDetails.setText("Block Details:");
        jPanel1.add(BlockDetails);
        BlockDetails.setBounds(30, 90, 180, 17);

        Hash1.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        Hash1.setForeground(new Color(255, 255, 255));
        Hash1.setText("Hash:");
        jPanel1.add(Hash1);
        Hash1.setBounds(60, 120, 130, 15);

        NoTrans1.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        NoTrans1.setForeground(new Color(255, 255, 255));
        NoTrans1.setText("No of Transactions:");
        jPanel1.add(NoTrans1);
        NoTrans1.setBounds(60, 180, 130, 15);

        Block1.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        Block1.setForeground(new Color(255, 255, 255));
        Block1.setText("Block Height:");
        jPanel1.add(Block1);
        Block1.setBounds(60, 160, 130, 15);

        Block.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        Block.setForeground(new Color(255, 255, 255));
        Block.setText("[BlockHeight]");
        jPanel1.add(Block);
        Block.setBounds(180, 160, 130, 15);

        Miner1.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        Miner1.setForeground(new Color(255, 255, 255));
        Miner1.setText("Miner:");
        jPanel1.add(Miner1);
        Miner1.setBounds(60, 200, 130, 15);

        Miner.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        Miner.setForeground(new Color(255, 255, 255));
        Miner.setText("[Miner]");
        jPanel1.add(Miner);
        Miner.setBounds(180, 200, 130, 15);

        Difficulty1.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        Difficulty1.setForeground(new Color(255, 255, 255));
        Difficulty1.setText("Difficulty:");
        jPanel1.add(Difficulty1);
        Difficulty1.setBounds(60, 220, 130, 15);

        Difficulty.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        Difficulty.setForeground(new Color(255, 255, 255));
        Difficulty.setText("[Difficulty]");
        jPanel1.add(Difficulty);
        Difficulty.setBounds(180, 220, 130, 15);

        GasUsed1.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        GasUsed1.setForeground(new Color(255, 255, 255));
        GasUsed1.setText("Gas Used:");
        jPanel1.add(GasUsed1);
        GasUsed1.setBounds(60, 240, 130, 15);

        GasUsed.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        GasUsed.setForeground(new Color(255, 255, 255));
        GasUsed.setText("[Gas]");
        jPanel1.add(GasUsed);
        GasUsed.setBounds(180, 240, 130, 15);

        GasLimit1.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        GasLimit1.setForeground(new Color(255, 255, 255));
        GasLimit1.setText("Gas Limit:");
        jPanel1.add(GasLimit1);
        GasLimit1.setBounds(60, 260, 130, 15);

        GasLimit.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        GasLimit.setForeground(new Color(255, 255, 255));
        GasLimit.setText("[GasLimit]");
        jPanel1.add(GasLimit);
        GasLimit.setBounds(180, 260, 130, 15);

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(1280, 730, 73, 23);

        PHash1.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        PHash1.setForeground(new Color(255, 255, 255));
        PHash1.setText("Parent Hash:");
        jPanel1.add(PHash1);
        PHash1.setBounds(60, 140, 130, 15);

        PHash.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        PHash.setForeground(new Color(255, 255, 255));
        PHash.setText("[ParentHash]");
        jPanel1.add(PHash);
        PHash.setBounds(180, 140, 130, 15);

        Transactions.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        Transactions.setForeground(new Color(255, 255, 255));
        Transactions.setText("Transactions:");
        jPanel1.add(Transactions);
        Transactions.setBounds(30, 290, 130, 17);

        Background.setIcon(new ImageIcon(getClass().getResource("/etherbkg.png"))); // NOI18N
        Background.setLabelFor(jPanel1);
        jPanel1.add(Background);
        Background.setBounds(0, 0, 1366, 768);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        parentFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlockScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlockScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlockScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlockScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlockScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton BackButton;
    private JLabel Background;
    private JLabel Block;
    private JLabel Block1;
    private JLabel BlockDetails;
    private JLabel Difficulty;
    private JLabel Difficulty1;
    private JLabel GasLimit;
    private JLabel GasLimit1;
    private JLabel GasUsed;
    private JLabel GasUsed1;
    private JLabel Hash;
    private JLabel Hash1;
    private JLabel Miner;
    private JLabel Miner1;
    private JLabel NoTrans;
    private JLabel NoTrans1;
    private JLabel PHash;
    private JLabel PHash1;
    private JLabel SkyScraper;
    private JLabel Transactions;
    private JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
