/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//import com.sun.org.apache.xerces.internal.impl.xpath.regex.ParseException;

import java.io.IOException;
import java.util.concurrent.ExecutionException;

/**
 *
 * @author Youssef Ziad
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SkyScraper = new javax.swing.JLabel();
        SearchingFor = new javax.swing.JLabel();
        SearchForBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        SearchBox1 = new javax.swing.JTextField();
        EnterSearchTerm = new javax.swing.JLabel();
        EnterSearchTerm1 = new javax.swing.JLabel();
        SearchBox2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        SkyScraper.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        SkyScraper.setForeground(new java.awt.Color(255, 255, 255));
        SkyScraper.setText("SkyScraper");
        jPanel1.add(SkyScraper);
        SkyScraper.setBounds(30, 20, 190, 42);

        SearchingFor.setForeground(new java.awt.Color(255, 255, 255));
        SearchingFor.setText("Searching for:");
        jPanel1.add(SearchingFor);
        SearchingFor.setBounds(30, 130, 80, 20);

        SearchForBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Account", "Block", "Transaction" }));
        SearchForBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchForBoxActionPerformed(evt);
            }
        });
        jPanel1.add(SearchForBox);
        SearchForBox.setBounds(140, 130, 150, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Advanced Search");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 180, 170, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loupe.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(550, 80, 40, 40);

        SearchBox1.setForeground(new java.awt.Color(204, 204, 204));
        SearchBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(SearchBox1);
        SearchBox1.setBounds(140, 90, 400, 20);

        EnterSearchTerm.setForeground(new java.awt.Color(255, 255, 255));
        EnterSearchTerm.setText("Enter Search Term:");
        jPanel1.add(EnterSearchTerm);
        EnterSearchTerm.setBounds(30, 90, 160, 20);

        EnterSearchTerm1.setForeground(new java.awt.Color(255, 255, 255));
        EnterSearchTerm1.setText("Enter Query:");
        jPanel1.add(EnterSearchTerm1);
        EnterSearchTerm1.setBounds(30, 220, 160, 20);

        SearchBox2.setForeground(new java.awt.Color(204, 204, 204));
        SearchBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(SearchBox2);
        SearchBox2.setBounds(140, 220, 400, 20);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loupe.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(550, 210, 40, 40);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etherbkg.png"))); // NOI18N
        Background.setLabelFor(jPanel1);
        jPanel1.add(Background);
        Background.setBounds(0, 0, 1366, 768);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchForBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchForBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchForBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        AccountScreen ac = null;
        TransactionScreen tc = null;
        BlockScreen bc = null;
        if(SearchForBox.getSelectedItem().equals("Account")) {
            try {
                ac = new AccountScreen(SearchBox1.getText(),this);
                ac.setVisible(true);
            } catch (ExecutionException e) {
                e.printStackTrace();
            } catch (InterruptedException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        else if(SearchForBox.getSelectedItem().equals("Transaction")){
            try {
                tc = new TransactionScreen(SearchBox1.getText(),this);
                tc.setVisible(true);
            } catch (ExecutionException e) {
                e.printStackTrace();
            } catch (InterruptedException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        else{
            try {
                try {
                    bc = new BlockScreen(Integer.parseInt(SearchBox1.getText()), this);
                }
                catch(NumberFormatException e2){
                    bc = new BlockScreen(SearchBox1.getText(), this);
                }
                bc.setVisible(true);
            } catch (ExecutionException e) {
                e.printStackTrace();
            } catch (InterruptedException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void SearchBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBox1ActionPerformed

    private void SearchBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            AdvancedScreen as = new AdvancedScreen(SearchBox2.getText(),this);
            as.setVisible(true);
            setVisible(false);
        } catch (ExecutionException e) {
            e.printStackTrace();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel EnterSearchTerm;
    private javax.swing.JLabel EnterSearchTerm1;
    private javax.swing.JTextField SearchBox1;
    private javax.swing.JTextField SearchBox2;
    private javax.swing.JComboBox<String> SearchForBox;
    private javax.swing.JLabel SearchingFor;
    private javax.swing.JLabel SkyScraper;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
